# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure

on:
  push:
    branches:
      - master # adjust this if you want it for 'main' or any other branch.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # Ensure Maven Compiler Plugin uses JDK 17
    - name: Update Maven Compiler Plugin for JDK 17
      run: |
        xmlstarlet ed -L \
          -u "//build/plugins/plugin[groupId='org.apache.maven.plugins' and artifactId='maven-compiler-plugin']/configuration/release" \
          -v '17' pom.xml

    - name: Build with Maven
      run: mvn clean install

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'FirstWebApp1234567' # Adjusted to use your provided App Service name
        slot-name: 'Production'
        publish-profile: ${{ secrets.YOUR_PUBLISH_PROFILE_SECRET }} # Make sure to replace this with the name of your GitHub secret.
        package: '*.jar'
